# version: '3.6'

services:
  app1:
    build:  # ./server/
      context: .
      dockerfile: ./server/Dockerfile
    expose:
      - 3000
    environment:
      - APPNAME=app1
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=Pineda7
    ports:
      - 3001:3000
      - 3002:3001
      - 3003:3002


  loadbalancer:

    build: ./haproxy
    expose:
      - 3000
    ports:
      - 3000:80
    depends_on:
      - app1
    networks:
     - default

 


networks:
  default:
